# Generated by Django 6.1.1 on 2026-09-22 09:32

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=5)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('season', models.CharField(max_length=10)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_games', to='lineups.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_games', to='lineups.team')),
            ],
        ),
        migrations.CreateModel(
            name='Possession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.SmallIntegerField()),
                ('start_time', models.IntegerField()),
                ('offensive_player_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=5)),
                ('defensive_player_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=5)),
                ('points', models.IntegerField(default=0)),
                ('fg_made', models.IntegerField(default=0)),
                ('fg_attempted', models.IntegerField(default=0)),
                ('fg2_made', models.IntegerField(default=0)),
                ('fg2_attempted', models.IntegerField(default=0)),
                ('fg3_made', models.IntegerField(default=0)),
                ('fg3_attempted', models.IntegerField(default=0)),
                ('ft_made', models.IntegerField(default=0)),
                ('ft_attempted', models.IntegerField(default=0)),
                ('offensive_rebounds', models.IntegerField(default=0)),
                ('defensive_rebounds', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField(default=0)),
                ('offensive_fouls', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('defensive_fouls', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineups.game')),
                ('defensive_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defensive_possessions', to='lineups.team')),
                ('offensive_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offensive_possessions', to='lineups.team')),
            ],
            options={
                'indexes': [models.Index(fields=['game', 'period'], name='lineups_pos_game_id_844939_idx')],
            },
        ),
    ]
